### PR TITLE
Add autoplay and disabling functionalities for videos

### PR DESCRIPTION
**Pull request by wszeborowskimateusz**

### CODE REVIEW

**Comment by kawa89** [comment]
Are changes to `TweetVideo` needed?
I see only adding and  passing down the flags, but not using them, or am I missing something?

**Comment by wszeborowskimateusz** [comment]
> Are changes to `TweetVideo` needed? I see only adding and passing down the flags, but not using them, or am I missing something?
Screenshot 2022-05-05 at 15 15 57

I think TweetVideo has already the implementation needed

**Comment by jpcodr** [comment]
Any updates on this?

**Review by kawa89 — APPROVED** [review]

**Comment by kawa89** [comment]
@wszeborowskimateusz 
Approved.

Can you prepare a release?

**Pull request merged**
