### PR TITLE
Upgrade dependencies (closes #69).

### LINKED ISSUE #69: Incompatible with Flutter v2.5.0
**Describe the bug**

Flutter v2.5.0 was recently released to the stable channel. This library has some compatibility issues (looks like largely from transitive dependencies). 

**To Reproduce**

When importing this library:

```
Launching lib/main.dart on Pixel 4a in debug mode...
Running Gradle task 'assembleDebug'...
../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../sdks/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../sdks/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);
```

When attempting to build the example app:

```
Running "flutter pub get" in example...
Launching lib/main.dart on Pixel 4a in debug mode...
Running Gradle task 'assembleDebug'...
../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../sdks/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../sdks/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);
                            ^
../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:100:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../../../sdks/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler(null);
                ^^^^^^^^^^^^^^^^^^^^^
../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:102:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../../../sdks/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler((dynamic message) async {
                ^^^^^^^^^^^^^^^^^^^^^
../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:114:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../../../sdks/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler(null);
                ^^^^^^^^^^^^^^^^^^^^^
../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:116:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../../../sdks/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler((dynamic message) async {
                ^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/nic/sdks/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/nic/sdks/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Expected behavior**
The library should be compatible with the latest stable channel.

**Additional context**
I will try to update the transitive dependencies and see if that resolves the issues (if so, will make a PR).

### PR DESCRIPTION
**Pull request by ndahlquist**
Test Plan:
- Build the Android test app successfully using Flutter v2.5.0.
- iOS app is crashing... seems to be an issue with the new version of wakelock?

```
Launching lib/main.dart on Nic’s iPhone X in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: WHHDQVVYPP
Running pod install...                                              3.5s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        11.1s
Xcode build done.                                           32.8s
(lldb) 2021-09-10 14:55:16.682214-0600 Runner[2069:998909] Warning: Unable to create restoration in progress marker file
*** Assertion failure in void FLTWakelockApiSetup(__strong id<FlutterBinaryMessenger> _Nonnull, NSObject<FLTWakelockApi> *__strong _Nullable)(), messages.m:130
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FLTWakelockApi api doesn't respond to @selector(toggleMsg:error:)'
*** First throw call stack:
(0x1a5d6325c 0x1b9af8480 0x1a5c70c98 0x1a6ff77e8 0x102f5dde8 0x102f5e88c 0x102bbd5c4 0x102bbd65c 0x102bbd960 0x1a86047b0 0x1a8606150 0x1a860bf24 0x1a7cde8c0 0x1a82032c8 0x1a7cdf3a8 0x1a7cdeeb0 0x1a7cdf1d4 0x1a7cdea90 0x1a7ce672c 0x1a811d38c 0x1a821b184 0x1a7ce6420 0x1a7b25ae4 0x1a7b24590 0x1a7b25730 0x1a860a0fc 0x1a8143a84 0x1b483dd00 0x1b48654fc 0x1b484b420 0x1b4865214 0x1a599b298 0x1a5973ff8 0x1b4889e04 0x1b4889acc 0x1b4889fa0 0x1a5ce28a8 0x1a5ce27a8 0x1a5ce1afc 0x1a5cdc018 0x1a5cdb7d0 0x1bc41d570 0x1a86082d0 0x1a860d84c 0x102bbdb04 0x1a59ba140)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001d1b517b0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1d1b517b0 <+8>:  b.lo   0x1d1b517cc               ; <+36>
    0x1d1b517b4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1d1b517b8 <+16>: mov    x29, sp
    0x1d1b517bc <+20>: bl     0x1d1b2e1fc               ; cerror_nocancel
Target 0: (Runner) stopped.
Installing and launching...                                        27.8s
Error launching application on Nic’s iPhone X.
```

### CODE REVIEW

**Comment by ndahlquist** [comment]
Wakelock issue is described here: https://github.com/creativecreatorormaybenot/wakelock/issues/140. Investigating

**Comment by ndahlquist** [comment]
Hmm, the suggested workaround of using `wakelock==0.5.3+3` is not compatible with Flutter v2.5.0. Need to wait for a fix from `wakelock` before we can update.

**Comment by kawa89** [comment]
👍  Nice work. Looking forward to finishing this PR. 
TBH I need to catch up on some work with this repo, hopefully this month, so I really appreciate your contribution so that this repo is up to date :)

**Comment by ndahlquist** [comment]
Good news @kawa89. They fixed the wakelock issue, and as of the latest commit, this builds and runs correctly on iOS and Android 👍

**Comment by kawa89** [comment]
LGTM. Merging :)
Thanks for the contribution.

**Review by kawa89 — APPROVED** [review]

**Pull request merged**
